### ISSUE TITLE
Link to solution

### ISSUE THREAD

**Issue by michaelhitzker** [htl-perg-2018-19-4bhif/vehicle-model-browser-exercise-michaelhitzker#1]
My link to the solution:
http://www.michaelhitzker.com/htl/vehicle-browser/

**Comment by rstropek** [comment]
Unfortunately I get a 404 error (not found) when accessing the link.

Greetings,
Rainer Stropek

**Comment by michaelhitzker** [comment]
Have you tried the new link (without models in the end)?

**Comment by rstropek** [comment]
Ah, ok. Now it works. Very nice 👍, the extra points are yours.

Greetings,
Rainer Stropek.
